'version' : "3"
services:
  pocket-gateway:
    build: .
    ports:
        - 8080:8080
    networks:
        - gateway
    command: "npm start"

    volumes:
      - ./:/gateway
    
networks:
    gateway: 
